//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowersInfo
    {
        public int ID { get; set; }
        public string Borrowers_Name { get; set; }
        public string Department { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Borrowed_Date { get; set; }
    }
}
